s3Endpoint:
  endpoint: "10.0.1.78"
  accessKey: "RJM9EQF3PBGKNCHHAEIX"
  secretKey: "3bUg4iwchFaiS3uWkV2UslxgPvwLcXgEV4oSWe4D"
  region: "default"
operation: DELETE  # PUT: create; DELETE: remove
bucketPrefile: "ppbk"
concurrent: 10
total: 100